### ISSUE TITLE
Nomic Bot Error

### ISSUE THREAD

**Issue by ArchmageInc** [nomicness/a-whole-new-world#106]
Version: newopen

Error: Cannot find module '../command-processors/open-processor.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/nomic-bot/dist/endpoint-processors/comment-processor.js:34:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

The bot has been reverted to the previous version: extensible

**Comment by ArchmageInc** [comment]
This was introduced in #105
